import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import { getScan } from '../services/api';
import { 
  FileText, Brain, Printer, ChevronLeft, 
  Calendar, Globe, Shield, Loader2, Download, Info
} from 'lucide-react';

const Report = () => {
  const { id } = useParams();
  const [scan, setScan] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchScan = async () => {
      try {
        const data = await getScan(id);
        setScan(data);
      } catch (error) {
        console.error('Failed to fetch report:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchScan();
  }, [id]);

  if (loading) return (
    <div className="flex flex-col items-center justify-center min-h-[calc(100vh-64px)] gap-4">
      <Loader2 className="animate-spin text-primary w-12 h-12" />
      <p className="text-gray-500">Generating AI Security Assessment...</p>
    </div>
  );

  if (!scan) return <div className="p-12 text-center">Report not found</div>;

  const severityCounts = {
    critical: scan.vulnerabilities?.filter(v => v.severity === 'critical').length || 0,
    high: scan.vulnerabilities?.filter(v => v.severity === 'high').length || 0,
    medium: scan.vulnerabilities?.filter(v => v.severity === 'medium').length || 0,
    low: scan.vulnerabilities?.filter(v => v.severity === 'low').length || 0,
  };

  return (
    <div className="max-w-[1000px] mx-auto p-8 pb-32">
      {/* Action Buttons - Hidden in Print */}
      <div className="flex justify-between items-center mb-10 print:hidden">
        <div className="flex gap-6">
          <Link to={`/scan/${id}`} className="flex items-center gap-2 text-gray-500 hover:text-white transition-colors font-bold group">
            <ChevronLeft size={20} className="group-hover:-translate-x-1 transition-transform" /> Back to Results
          </Link>
          <Link to="/dashboard" className="hidden sm:flex items-center gap-2 text-gray-500 hover:text-white transition-colors font-bold">
            Dashboard
          </Link>
        </div>
        <button 
          onClick={() => window.print()}
          className="px-6 py-2.5 bg-primary text-black font-bold rounded-xl flex items-center gap-2 hover:scale-105 transition-all shadow-[0_0_20px_rgba(0,255,136,0.3)]"
        >
          <Printer size={18} /> Export PDF
        </button>
      </div>

      {/* Report Header Card */}
      <div className="bg-card border border-border rounded-3xl p-10 mb-8 print:bg-white print:text-black print:border-black">
        <div className="flex justify-between items-start mb-12">
          <div className="space-y-2">
            <div className="flex items-center gap-3 text-primary print:text-black">
              <div className="p-2 bg-primary/10 rounded-lg print:border print:border-black">
                <FileText size={24} />
              </div>
              <span className="font-black text-xl tracking-tighter uppercase">Security Assessment Report</span>
            </div>
            <p className="text-gray-500 text-sm font-medium print:text-gray-700">Generated by VulnScanner AI Engine v2.4</p>
          </div>
          <div className="w-16 h-16 rounded-full bg-white/5 border border-border flex items-center justify-center text-primary print:border-black print:text-black">
             <Shield size={32} />
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-12">
          <div className="p-5 bg-background border border-border rounded-2xl print:border-black">
            <div className="text-[10px] font-bold text-gray-500 uppercase mb-2">Target Infrastructure</div>
            <div className="flex items-center gap-2 font-mono text-sm">
              <Globe size={14} className="text-primary" />
              {scan.target_url}
            </div>
          </div>
          <div className="p-5 bg-background border border-border rounded-2xl print:border-black">
            <div className="text-[10px] font-bold text-gray-500 uppercase mb-2">Assessment Date</div>
            <div className="flex items-center gap-2 text-sm font-bold">
              <Calendar size={14} className="text-primary" />
              {new Date(scan.created_at).toLocaleString()}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'Critical', count: severityCounts.critical, color: 'text-red-500', bg: 'bg-red-500/10' },
            { label: 'High', count: severityCounts.high, color: 'text-orange-500', bg: 'bg-orange-500/10' },
            { label: 'Medium', count: severityCounts.medium, color: 'text-yellow-500', bg: 'bg-yellow-500/10' },
            { label: 'Low', count: severityCounts.low, color: 'text-blue-500', bg: 'bg-blue-500/10' },
          ].map((s, i) => (
            <div key={i} className={`p-4 rounded-2xl border border-border text-center print:border-black ${s.bg}`}>
              <div className={`text-2xl font-black ${s.color} print:text-black`}>{s.count}</div>
              <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* AI Analysis Section */}
      <div className="bg-card border border-border rounded-3xl p-10 print:bg-white print:text-black print:border-black">
        <div className="flex items-center gap-3 mb-8 border-b border-border pb-6 print:border-black">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary print:border print:border-black print:text-black">
            <Brain size={22} />
          </div>
          <h2 className="text-2xl font-bold">AI Analysis & <span className="text-primary print:text-black">Remediation Guide</span></h2>
        </div>

        {scan.report?.ai_summary ? (
          <div className="prose prose-invert prose-primary max-w-none 
            print:prose-slate
            prose-headings:font-bold prose-h2:text-primary prose-h2:border-b prose-h2:border-border prose-h2:pb-2 prose-h2:mt-10
            prose-p:text-gray-400 prose-p:leading-relaxed
            prose-li:text-gray-400
            prose-code:text-primary prose-code:bg-background prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded
            prose-strong:text-white
          ">
            <ReactMarkdown className="markdown-content">
              {scan.report.ai_summary}
            </ReactMarkdown>
          </div>
        ) : (
          <div className="py-20 text-center flex flex-col items-center gap-4 text-gray-600">
            <Info size={40} className="opacity-20" />
            <p>No AI-generated report available for this scan.</p>
          </div>
        )}
      </div>

      <div className="mt-12 text-center text-[10px] text-gray-600 font-bold uppercase tracking-[0.2em] print:text-black">
        End of Security Assessment - VulnScanner AI
      </div>
    </div>
  );
};

export default Report;
